# Generated by Django 3.2.4 on 2021-06-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcsv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='csv_file',
            field=models.FileField(upload_to='csv/'),
        ),
    ]
