# Generated by Django 3.2.4 on 2021-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcsv', '0002_alter_csvdata_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
