# Generated by Django 3.2.4 on 2021-06-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcsv', '0003_alter_csvdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='json_file',
            field=models.FileField(null=True, upload_to='json/'),
        ),
    ]
