# Generated by Django 3.2.4 on 2021-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcsv', '0004_csvdata_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvdata',
            name='json_file',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='json_data',
            field=models.CharField(max_length=270200, null=True),
        ),
    ]
